name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - name: Set up Node toolchain
        uses: actions/setup-node@v4

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm install

      - name: Build source
        run: spago build --censor-stats --strict --pedantic-packages

      - name: Run tests
        run: spago test --censor-stats --strict --pedantic-packages

      - name: Verify formatting
        run: purs-tidy check src test
